### PR TITLE
Fix passing null to parameter of type string

### LINKED ISSUE #47: RequestSignature::normalizeParameters uses deprecated invocation
```http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated```

In `src/HttpClient/Plugin/RequestSignature.php` on line `87`.

Affected version: `1.25.0`
PHP version: `8.1.0`

## Context

```php
private function normalizeParameters(array $params)
{
    uksort($params, 'strcmp');

    return http_build_query($params, null, '&', PHP_QUERY_RFC3986);
}
```

## Suggested solution

```php
private function normalizeParameters(array $params)
{
    uksort($params, 'strcmp');

    return http_build_query($params, '', '&', PHP_QUERY_RFC3986);
}
```

### PR DESCRIPTION
**Pull request by johmanx10**
Passing `null` to internal PHP functions, with argument type of string
is deprecated in PHP 8.1.

This can be easily fixed by supplying empty strings instead.

Closes #47

### CODE REVIEW

**Comment by johmanx10** [comment]
@wissem This PR should tackle support for PHP 8.1.
However, I completely base that on the completeness of PHPUnit tests.

File: src/WebhookSignature.php [hunk 1]
```diff
@@ -19,7 +19,7 @@ public function __construct($secret)
      */
     public function validate($signature, $payload)
     {
-        $payloadSignature = 'sha1='.hash_hmac('sha1', $payload, $this->secret);
+        $payloadSignature = 'sha1='.hash_hmac('sha1', $payload ?? '', $this->secret);
```
Comment (glaubinix) [inline src/WebhookSignature.php:22]: Can you also update the method signature to indicate that `null` is now a valid value for `$payload`?

**Review by glaubinix — COMMENTED** [review]
Thank you! I'll have a look at the rest of our code to see if there is anything else we need to update. Feel free to ignore the PHP8 build failure. I'll get this fixed once this is merged.
